import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";
import Auth from "./auth";
import Landingpage from "./landingpage";

const Home: NextPage = (props) => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-black">
        {/* <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]"> */}

        {/* Auth for keeping data later */}
        {/* <Auth /> */}
        <Landingpage />
      </main>
    </>
  );
};

export default Home;
