import { type NextPage } from "next";
import Head from "next/head";

import Landingpage from "./landingpage";

const Home: NextPage = (props: any) => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-black">
        <Landingpage />
      </main>
    </>
  );
};

export default Home;
