import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";
import UserSignIn from "./UserSignIn";

const Home: NextPage = (props) => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-white">
        {/* <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]"> */}
        <div>Hi</div>
        <UserSignIn />
      </main>
    </>
  );
};

export default Home;
